### ISSUE TITLE
Character portrait images have display artefacts

### ISSUE THREAD

**Issue by chrisgregan** [FungusGames/Fungus#92]
I think there is an internal optimisation on the Image class that crops the Image vertices to only render the visible pixels in the sprite texture. It seems to be based off whatever sprite is assigned to the image at the start. 

![screen shot 2015-03-27 at 14 01 22](https://cloud.githubusercontent.com/assets/3728355/6869161/d26e7afa-d489-11e4-91ed-3010017e6ed8.png)

**Comment by unknowndevice** [comment]
Hi hi! Does doing this prevent you texture packing sprites?  I've noticed that if you have a sprite of say size 256x512 that it will tile unless you encase the sprite in spacing that equals 1000x1000.

Doing that to prevent tiling means you can't do generic texture packing because it'll remove that white spacing.

I haven't looked at how the resource handling works for portraits so correct me if I'm wrong, but I assume texture packing is something you want to be able to do?

**Comment by chrisgregan** [comment]
Yes, this is a pretty significant limitation of the portrait system currently. There can be a lot of wasted space around the portraits and it makes it hard / impossible to atlas the sprites.

I'll reopen this issue to see if we can find a better solution. All the problems here stem back to the use of a custom shader for the cross fade effect. I'm pretty sure we could get the same effect by duplicating the portrait image, changing the texture on one of the sprites and then fading one sprite down and one sprite up - no shaders needed.

**Comment by chrisgregan** [comment]
Fixed the tiling issue by switching to a pair of crossfading images instead of using a custom material and shader. Also fixed a number of other issues in the Portrait and Stage system and added an integration test to verify correct behaviour in future.
